# Generated by Django 3.2.7 on 2023-02-04 11:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('long_url', models.URLField(blank=True, null=True, verbose_name='Long URL')),
                ('subpart', models.CharField(blank=True, max_length=128, null=True, verbose_name='Subpart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('visit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Visit')),
                ('short_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkshortener.shortlink')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
