# Generated by Django 3.2.7 on 2023-02-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkvisit',
            options={'verbose_name': 'Link visit', 'verbose_name_plural': 'Link visits'},
        ),
        migrations.AlterModelOptions(
            name='shortlink',
            options={'verbose_name': 'Short link', 'verbose_name_plural': 'Short links'},
        ),
        migrations.AlterField(
            model_name='linkvisit',
            name='visit',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Visit'),
        ),
    ]
