# Generated by Django 3.2.7 on 2023-02-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('linkshortener', '0002_auto_20230204_1448'), ('linkshortener', '0003_shortlink_session_key'), ('linkshortener', '0004_auto_20230207_0728')]

    dependencies = [
        ('linkshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkvisit',
            options={'verbose_name': 'Link visit', 'verbose_name_plural': 'Link visits'},
        ),
        migrations.AlterModelOptions(
            name='shortlink',
            options={'verbose_name': 'Short link', 'verbose_name_plural': 'Short links'},
        ),
        migrations.AddField(
            model_name='shortlink',
            name='session_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Session key'),
        ),
        migrations.RemoveField(
            model_name='linkvisit',
            name='visit',
        ),
        migrations.AddField(
            model_name='linkvisit',
            name='number_of_visits',
            field=models.PositiveIntegerField(default=0, verbose_name='Number_of_visits'),
        ),
    ]
