# Generated by Django 3.2.7 on 2023-02-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshortener', '0002_auto_20230204_1448_squashed_0004_auto_20230207_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkvisit',
            name='number_of_visits',
        ),
        migrations.AddField(
            model_name='linkvisit',
            name='visits_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visits count'),
        ),
    ]
